# Generated by Django 5.2.4 on 2025-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solfeggio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solfeggiofrequency',
            name='frequency_hz',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
