# Generated by Django 5.2.4 on 2025-08-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractivity_details_alter_useractivity_action_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='details',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='app_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
