# Generated by Django 5.2.4 on 2025-08-15 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solfeggio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreathworkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('Bhastrika', 'Bhastrika'), ('Kapalabhati', 'Kapalabhati'), ('Wim Hof', 'Wim Hof'), ('Mula Bandha', 'Uddiyana Bandha'), ('Microcosmic Orbit', 'Microcosmic Orbit'), ('Other', 'Other')], max_length=100)),
                ('duration', models.PositiveBigIntegerField(help_text='Duration in minutes')),
                ('energy_level', models.PositiveBigIntegerField(help_text='Rate energy 1-10')),
                ('experience_notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breathwork_sessions', to=settings.AUTH_USER_MODEL)),
                ('solfeggio_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solfeggio.solfeggiofrequency')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
