# Generated by Django 5.2.4 on 2025-08-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breathwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breathworksession',
            old_name='User',
            new_name='user',
        ),
    ]
