# Generated by Django 5.2.4 on 2025-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breathwork', '0002_rename_user_breathworksession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breathworksession',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='breathworksession',
            name='energy_level',
            field=models.PositiveIntegerField(help_text='Rate energy 1-10'),
        ),
        migrations.AlterField(
            model_name='breathworksession',
            name='technique',
            field=models.CharField(choices=[('bhastrika', 'Bhastrika'), ('kapalabhati', 'Kapalabhati'), ('wim Hof', 'Wim Hof'), ('mula Bandha', 'Mula Bandha'), ('uddiyana bandha', 'Uddiyana Bandha'), ('microcosmic Orbit', 'Microcosmic Orbit'), ('Other', 'Other')], max_length=100),
        ),
    ]
