# Generated by Django 5.2.4 on 2025-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sexualenergy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexualenergylog',
            name='energy_level',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5),
        ),
    ]
