# Generated by Django 5.2.4 on 2025-08-16 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solfeggio', '0001_initial'),
        ('visualizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisualizatioAffirmation',
            new_name='VisualizationAffirmation',
        ),
    ]
