# Generated by Django 5.2.4 on 2025-08-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solfeggio', '0002_alter_solfeggiofrequency_frequency_hz'),
        ('visualizations', '0002_rename_visualizatioaffirmation_visualizationaffirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='visualizationaffirmation',
            options={'ordering': ['-date_created'], 'verbose_name': 'Affirmation', 'verbose_name_plural': 'Affirmations'},
        ),
        migrations.AddField(
            model_name='visualizationaffirmation',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='visualizationaffirmation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visualizationaffirmation',
            name='solfeggio_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affirmations', to='solfeggio.solfeggiofrequency'),
        ),
        migrations.RemoveField(
            model_name='visualizationaffirmation',
            name='tags',
        ),
        migrations.AddField(
            model_name='visualizationaffirmation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='affirmations', to='visualizations.tag'),
        ),
    ]
