# Generated by Django 5.2.4 on 2025-08-23 09:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldshowers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coldshowerlog',
            options={'ordering': ['-date'], 'verbose_name': 'Cold Shower Log', 'verbose_name_plural': 'Cold Shower Logs'},
        ),
        migrations.AlterField(
            model_name='coldshowerlog',
            name='resistance_level',
            field=models.PositiveIntegerField(default=5, help_text='Mental resistance level (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='coldshowerlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_shower_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
