# Generated by Django 5.2.4 on 2025-08-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coldshowers', '0002_alter_coldshowerlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldshowerlog',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of the shower in minutes'),
        ),
        migrations.AddField(
            model_name='coldshowerlog',
            name='water_temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Optional: water temperature in °C', max_digits=4, null=True),
        ),
    ]
