# Generated by Django 5.2.4 on 2025-08-22 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepStageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sleep_start', models.DateTimeField()),
                ('sleep_end', models.DateTimeField()),
                ('total_duration', models.DurationField(blank=True, null=True)),
                ('quality_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5)),
                ('mood_after', models.CharField(blank=True, max_length=50, null=True)),
                ('rituals', models.TextField(blank=True, null=True)),
                ('dream_notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SleepSolfeggioRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('sleep_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solfeggio_recommendations', to='sleep.sleeplog')),
            ],
        ),
        migrations.CreateModel(
            name='SleepStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('sleep_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='sleep.sleeplog')),
                ('stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sleep.sleepstagetype')),
            ],
        ),
    ]
