# Generated by Django 5.2.4 on 2025-08-23 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0001_initial'),
        ('solfeggio', '0002_alter_solfeggiofrequency_frequency_hz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleeplog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='rituals',
            field=models.TextField(blank=True, help_text='Bedtime rituals or practices', null=True),
        ),
        migrations.AlterField(
            model_name='sleeplog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sleepsolfeggiorecommendation',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solfeggio.solfeggiofrequency'),
        ),
        migrations.AddIndex(
            model_name='sleeplog',
            index=models.Index(fields=['user', 'date'], name='sleep_sleep_user_id_dba909_idx'),
        ),
    ]
