# Generated by Django 5.2.4 on 2025-08-27 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionlog',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='energy_effect',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='How energized did you feel after eating? (1-10)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='food_items',
            field=models.TextField(help_text='List the foods consumed in this meal'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='hydration_liters',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Liters of water', max_digits=5),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='mood_effect',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=5, help_text='Mood change after eating (1-10)'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='supplements',
            field=models.TextField(blank=True, help_text='Any supplements taken', null=True),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='nutritionlog',
            index=models.Index(fields=['user', 'date'], name='nutrition_n_user_id_d3197c_idx'),
        ),
    ]
