# Generated by Django 5.2.4 on 2025-08-28 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_nutritionlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionlog',
            name='calories',
            field=models.PositiveIntegerField(help_text='Total calories consumed'),
        ),
        migrations.AlterField(
            model_name='nutritionlog',
            name='hydration_liters',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Liters of water consumed', max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='nutritionlog',
            constraint=models.UniqueConstraint(fields=('user', 'meal_type', 'date'), name='unique_meal_per_day'),
        ),
    ]
