# Generated by Django 5.2.4 on 2025-08-23 09:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['-date'], 'verbose_name': 'Workout Session', 'verbose_name_plural': 'Workout Sessions'},
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='energy_effect',
            field=models.PositiveIntegerField(default=5, help_text='Energy effect rating (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='type',
            field=models.CharField(choices=[('yoga', 'Yoga'), ('cardio', 'Cardio'), ('strength', 'Strength Training'), ('pilates', 'Pilates'), ('stretching', 'Stretching'), ('meditation', 'Meditative Movement')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
