# Generated by Django 5.2.4 on 2025-08-16 05:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solfeggio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chakra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('root', 'Root (Root (Muladhara))'), ('sacral', 'Sacral (Svadhisthana)'), ('solar_plexus', 'Solar Plexus (Manipura)'), ('heart', 'Heart (Anahata)'), ('throat', 'Throat (Vishuddha)'), ('third_eye', 'Third Eye (Ajna)'), ('crown', 'Crown (Sahasrara)')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('sanskrit_name', models.CharField(max_length=60)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('element', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChakraLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('balanced', 'Balanced'), ('open', 'Open'), ('blocked', 'Blocked'), ('underactive', 'Underactive'), ('overactive', 'Overactive')], max_length=20)),
                ('intensity', models.PositiveIntegerField(blank=True, help_text='1-10 (optional)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chakra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='chakras.chakra')),
                ('solfeggio_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chakra_logs', to='solfeggio.solfeggiofrequency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chakra_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='chakras_cha_user_id_2b3177_idx'), models.Index(fields=['chakra'], name='chakras_cha_chakra__77c1ca_idx')],
            },
        ),
    ]
