# Generated by Django 5.2.4 on 2025-08-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chakras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chakra',
            name='code',
            field=models.CharField(choices=[('root', '(Root (Muladhara))'), ('sacral', 'Sacral (Svadhisthana)'), ('solar_plexus', 'Solar Plexus (Manipura)'), ('heart', 'Heart (Anahata)'), ('throat', 'Throat (Vishuddha)'), ('third_eye', 'Third Eye (Ajna)'), ('crown', 'Crown (Sahasrara)')], max_length=20, unique=True),
        ),
    ]
