# Generated by Django 5.2.4 on 2025-08-23 09:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0002_rename_meditationseesion_meditationsession'),
        ('solfeggio', '0002_alter_solfeggiofrequency_frequency_hz'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meditationsession',
            options={'ordering': ['-date'], 'verbose_name': 'Meditation Session', 'verbose_name_plural': 'Meditation Sessions'},
        ),
        migrations.AddField(
            model_name='meditationsession',
            name='clarity_score',
            field=models.PositiveIntegerField(blank=True, help_text='Rate clarity 1–10', null=True),
        ),
        migrations.AddField(
            model_name='meditationsession',
            name='solfeggio_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solfeggio.solfeggiofrequency'),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to=settings.AUTH_USER_MODEL),
        ),
    ]
