# Generated by Django 5.2.4 on 2025-08-27 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0003_alter_meditationsession_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationsession',
            name='focus_level',
            field=models.PositiveIntegerField(blank=True, help_text='Rate focus 1-10', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='meditationsession',
            name='spirit_level',
            field=models.CharField(choices=[('low', 'Low - grounded, but not very connected'), ('balanced', 'Balanced - stable and centered'), ('elevated', 'Elevated - deeply connected, high energy'), ('transcendent', 'Transcendent - unity, deep spiritual experience')], default='balanced', max_length=20),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='clarity_score',
            field=models.PositiveIntegerField(blank=True, help_text='Rate clarity', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Duration in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)]),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='mood_after',
            field=models.CharField(blank=True, choices=[('calm', 'Calm'), ('relaxed', 'Relaxed'), ('happy', 'Happy'), ('grateful', 'Grateful'), ('focused', 'Focused'), ('energized', 'Energized'), ('neutral', 'Neutral'), ('thoughtful', 'Thoughtful'), ('tired', 'Tired')], max_length=50),
        ),
        migrations.AlterField(
            model_name='meditationsession',
            name='mood_before',
            field=models.CharField(blank=True, choices=[('calm', 'Calm'), ('relaxed', 'Relaxed'), ('happy', 'Happy'), ('grateful', 'Grateful'), ('focused', 'Focused'), ('energized', 'Energized'), ('neutral', 'Neutral'), ('thoughtful', 'Thoughtful'), ('tired', 'Tired')], max_length=50),
        ),
    ]
