# Generated by Django 5.2.4 on 2025-08-29 04:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('goal_type', models.CharField(choices=[('count', 'Count-based (e.g., sessions, reps)'), ('duration', 'Time-based (e.g., minutes per day)'), ('streak', 'Streak-based (do it every day)'), ('custom', 'Custom / subjective')], default='streak', max_length=20)),
                ('target_value', models.FloatField(blank=True, help_text='Optional numeric target (e.g., 20 minutes/day or 10 sessions).', null=True)),
                ('unit', models.CharField(blank=True, help_text="Optional unit like 'min', 'sessions', 'km'.", max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('left', 'Left')], default='joined', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='challenges_joined', through='challenges.ChallengeMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('value', models.FloatField(blank=True, help_text='Numeric progress (e.g., minutes, reps). Optional for streak/custom.', null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='challengemembership',
            index=models.Index(fields=['challenge', 'user'], name='challenges__challen_c1e6fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengemembership',
            unique_together={('challenge', 'user')},
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['visibility', 'start_date', 'end_date'], name='challenges__visibil_c47c55_idx'),
        ),
        migrations.AddIndex(
            model_name='challenge',
            index=models.Index(fields=['created_by'], name='challenges__created_a1a12c_idx'),
        ),
        migrations.AddIndex(
            model_name='challengeprogress',
            index=models.Index(fields=['challenge', 'user', 'date'], name='challenges__challen_129562_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeprogress',
            unique_together={('challenge', 'user', 'date')},
        ),
    ]
