# Generated by Django 5.2.4 on 2025-08-18 09:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solfeggio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoulNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('mood', models.CharField(blank=True, choices=[('happy', 'Happy'), ('neutral', 'Neutral'), ('sad', 'Sad'), ('reflective', 'Reflective'), ('grateful', 'Grateful'), ('motivated', 'Motivated'), ('focused', 'Focused'), ('anxious', 'Anxious'), ('inspired', 'Inspired'), ('calm', 'Calm'), ('peaceful', 'Peaceful'), ('creative', 'Creative'), ('flow_state', 'Flow State'), ('energetic', 'Energetic'), ('spiritually_connected', 'Spiritually Connected')], max_length=50, null=True)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('solfeggio_frequency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solfeggio.solfeggiofrequency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
