# Generated by Django 5.2.4 on 2025-08-23 09:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soulnotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soulnote',
            options={'ordering': ['-date_created'], 'verbose_name': 'Soul Note', 'verbose_name_plural': 'Soul Notes'},
        ),
        migrations.AddField(
            model_name='soulnote',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soulnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='soulnote',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
